config/routes.rb
Rails.application.routes.draw do
  get 'password' => 'password#index'
  post 'password' => 'password#index'

  resources :carts

  root 'carts#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    helper_method :admin?

    def admin?
        session[:password] == Rails.application.secrets.password 
    end

    def check_for_admin
        redirect_to root_path unless admin?
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  before_action :check_for_admin, only: [:edit, :update, :new, :create, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to root_path, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to root_path, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
        format.js {}
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
      @id = @cart.id
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
      format.js {}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:name, :location)
    end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  def index
      if params[:password]
          session[:password] = params[:password]
          redirect_to root_path
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/destroy.js.erb
$("#cart<%= @id %>").parent().fadeOut(500, function() { $(this).remove()});

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<table>
    <tbody>
    <% @carts.each do |cart| %>
        <tr>
        <td><%= link_to image_tag('logo.png'), cart %></td>
        <td id="cart<%= cart.id %>"><span class="cartName"><%= cart.name %></span><br/><span class="cartLocation"><%= cart.location %></span></td>
        <% if admin? %>
            <td>
            <%= form_for cart, :remote => true do |f| %>
                <%= f.text_field :location %><br/>
                <%= f.submit "Update Location" %>
            <% end %>
        </td>
        <td>
            <%= link_to "Remove Cart", cart_path(cart), :method => :delete, :remote => true, :confirm => 'Are you sure?' %>
        </td>
        <% end %>
    </tr>
<% end %>
    </tbody>
</table>

<% if admin? %>
<br>

<%= link_to 'New Cart', new_cart_path %>
<%= link_to "Log Out", password_path(:password => '') %>
<% else %>
    <%= link_to "Authenticate", password_path %>
<% end %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cart.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @cart.location %>
</p>

<% if admin? %><%= link_to 'Edit', edit_cart_path(@cart) %> | <% end %>
<%= link_to 'Back', carts_path %>

app/views/carts/update.js.erb
$('#cart<%= @cart.id %>').html('<span class="cartName"><%= @cart.name %></span><br/><span class="cartLocation"><%= @cart.location %></span>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Dude, Where's My Cart?</title>
    <link href='http://fonts.googleapis.com/css?family=Indie+Flower|Oxygen:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
    <%= image_tag 'logo.png' %>
    <h1>Dude, Where's My Cart?</h1>
</header>

<div id="main">
    <%= yield %>
</div>

</body>
</html>

app/views/password/index.html.erb
<%= form_tag password_path do %>
    <%= text_field_tag :password %>
    <%= submit_tag "Authenticate" %>
<% end %>